# Generated by Django 3.2.9 on 2022-04-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('specialite', models.CharField(max_length=50)),
                ('departement', models.CharField(max_length=50)),
                ('anneeEtude', models.CharField(max_length=50)),
            ],
        ),
    ]
