# Generated by Django 3.2.9 on 2022-04-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='startupIdea',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
