# Generated by Django 3.2.9 on 2022-04-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_participant_faculte'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='equipe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='porteurDeProjet',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
