# Generated by Django 3.2.9 on 2022-04-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20220421_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='skills',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
